#!/bin/bash

set -eux -o pipefail

# Set paths for running various scripts.
export shared_files='./files/shared'
export shared_scripts='./scripts/shared'
export linux_files='./files/linux'
export linux_scripts='./scripts/linux'
export macos_files='./files/macos'
export macos_scripts='./scripts/macos'

if [[ $(uname) == Linux ]]; then
    # Note: this assumes Ubuntu Linux.

    # Determine if gnome-desktop is installed. If it is, install gnome-specific customizations.
    readonly GNOME_INSTALLED=$(apt list --installed 2>/dev/null | grep gnome-desktop; echo $?)

    # Make customizations specific to GUI environments.
    bash ${linux_scripts}/install-debs-gui.sh
    bash ${linux_scripts}/install-terminator.sh
    bash ${linux_scripts}/install-yakuake.sh
    bash ${linux_scripts}/install-sublime.sh
    bash ${linux_scripts}/install-chrome.sh
    bash ${linux_scripts}/install-slack.sh
    bash ${linux_scripts}/install-hack-font.sh

    # Make customizations specific to Gnome environments.
    if [[ GNOME_INSTALLED ]]; then
        bash ${linux_scripts}/configure-gnome.sh
    fi
elif [[ $(uname) == Darwin ]]; then
    echo "No GUI items for MacOS have been configured."
fi

# Unset exported variables.
unset shared_files
unset shared_scripts
unset linux_files
unset linux_scripts
unset macos_files
unset macos_scripts
