#!/bin/sh

# Install packages.
sudo apt-get install -y \
	terminator

# Set up ~/bin
mkdir -p ~/bin
cp -n ./bin/ipaddr ~/bin/ipaddr; chmod +x ~/bin/ipaddr
cp -n ./bin/full-upgrade ~/bin/full-upgrade; chmod +x ~/bin/full-upgrade
cp -n ./bin/battery ~/bin/battery; chmod +x ~/bin/battery

# Make a code directory.
mkdir -p ~/code

# Set up configuration files.
cp -n ./.bashrc ~/.bashrc
mkdir -p ~/.config/terminator
cp -n ./.config/terminator/config ~/.config/terminator/config

# Add bgrep.
if [ -e ~/bin/bgrep ]; then cp ~/bin/bgrep ~/bin/bgrep.bak; fi
gcc -O2 -x c -o ~/bin/bgrep ./plugins/bgrep/bgrep.c

# Leave installer.
echo Finished installation.
