#!/bin/bash

if [[ $(uname) == Linux ]]; then
    upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage | sed -E "s/.+?: +(.+?%).*/\1/"
elif [[ $(uname) == Darwin ]]; then
    pmset -g batt | grep -i battery | cut -d";" -f1 | sed "s/.*InternalBattery-.//" | tr -d '[:space:]'; echo
fi
