#!/bin/bash
# shellcheck disable=SC2046
set -x

# Stop all containers.
docker kill $(docker ps -q)

# Delete all containers.
docker rm -f $(docker ps -aq)

# Delete all dangling volumes.
docker volume rm -f $(docker volume ls -qf dangling=true)

# Delete all images.
docker rmi -f $(docker images -q)

# Prune Docker, whatever that means.
docker system prune -a -f
