#!/bin/bash

# Set up venv.
source "${HOME}/.venv_setup"
if [[ $(lsvirtualenv -b | grep glances &>/dev/null; echo $?) != 0 ]]; then
    mkvirtualenv glances
    pip install --upgrade glances
fi
workon glances

# Start glances.
glances
