#!/bin/bash

PROFILE=${1:-default}

source "${HOME}/.venv_setup"
if ! lsvirtualenv -b | grep "^aws$" &>/dev/null; then
    echo "creating 'aws' virtualenv..."
    mkvirtualenv aws
fi
workon aws
if ! pip freeze | grep "aws-mfa=" &>/dev/null; then
     echo "installing aws-mfa..."
     pip install aws-mfa
fi

set -eux -o pipefail

# Authenticate via MFA.
aws-mfa --profile "${PROFILE}" --force

# Rotate the access key.
export AWS_PROFILE="${PROFILE}"
aws-rotate-iam-keys "${PROFILE}"
